export const industries = [
  "AI and ML",
  "AdTech",
  "Advertising",
  "Aerospace",
  "Banking",
  "Big Data",
  "Blockchain",
  "Clean Energy",
  "Cloud Computing",
  "Construction",
  "Consultancy",
  "Cyber Security",
  "E-Commerce",
  "EdTech",
  "Energy",
  "Enterprise Software",
  "Entertainment",
  "Environmental Management",
  "Finance",
  "Fintech",
  "Hardware",
  "Health and Wellness",
  "Hospitality",
  "Logistics",
  "Manufacturing",
  "Marketplace",
  "Medicine",
  "Non-Profit",
  "Retail",
  "Social",
  "Transport and Travel",
  "Utilities",
  "Venture Capital",
  "Video Games",
  "Virtual Reality",
];
