export const preferredRoles = [
"Back End Developer",
"Data Scientist",
"Front End Developer",
"ML Engineer",
"Full Stack Developer",
"Data Engineer",
"Product Manager",
"Systems Engineer",
"Devops Engineer",
"Android Engineer",
"iOS Engineer",
"Product Designer",
"Security Engineer",
"Network Engineer",
"Consulting",
"Finance",
"IT System Administrator",
"Hardware Engineer",
"Graphic Designer",
"Business Operations",
"Marketing",
"Sales",
"Content Strategist",
"Recruiting",
"Supply Chain Management",
"Accounting",
"HR",
"Logistics Coordinator",
"Legal",
"Copywriting"
];
