export const UserConstants = {
    VERIFYING_USER_LOGIN: 'VERIFYING_USER_LOGIN',
    VERIFYING_USER_LOGIN_SUCCESS: 'VERIFYING_USER_LOGIN_SUCCESS',
    VERIFYING_USER_LOGIN_FAILURE: 'VERIFYING_USER_LOGIN_FAILURE',
    USER_LOGGING_IN: 'USER_LOGGING_IN',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGING_OUT: 'USER_LOGGING_OUT',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FALIURE: 'USER_SIGNUP_FALIURE',
    USER_EMAIL_VERIFIED: 'USER_EMAIL_VERIFIED',
    USER_EMAIL_VERIFICATION_FALIURE: 'USER_EMAIL_VERIFICATION_FALIURE',
    USER_AWAITING_EMAIL_VERIFICATION: 'USER_AWAITING_EMAIL_VERIFICATION',
    USER_AWAITING_PASSWORD_RESET_VERIFICATION: 'USER_AWAITING_PASSWORD_RESET_VERIFICATION',
    USER_PASSWORD_RESET_FAILURE: 'USER_PASSWORD_RESET_FAILURE',
    USER_PASSWORD_RESET_SUCCESS: 'USER_PASSWORD_RESET_SUCCESS',
    USER_AWAITING_TERMINATION: 'USER_AWAITING_TERMINATION',
    USER_TERMINATION_FAILURE: 'USER_TERMINATION_FAILURE',
    USER_TERMINATION_SUCCESS: 'USER_TERMINATION_SUCCESS',
    CLEAR_AUTH_ERRORS: 'CLEAR_AUTH_ERRORS',
    GET_AUTH_ERRORS: 'GET_AUTH_ERRORS',
    CLEAR_AUTH_STATE: 'CLEAR_AUTH_STATE',
    LOADING_USER: 'LOADING_USER',
    LOADING_USER_FAILURE: 'LOADING_USER_FAILURE',
    LOADING_USER_SUCCESS: 'LOADING_USER_SUCCESS',
    HASHING_TO_STORAGE: 'HASHING_TO_STORAGE',
    HASHED_TO_STORAGE: 'HASHED_TO_STORAGE',
    HASHING_TO_STORAGE_FAIL: 'HASHING_TO_STORAGE_FAIL',
    REMOVED_FROM_STORAGE: 'REMOVED_FROM_STORAGE',
    REMOVING_FROM_STORAGE: 'REMOVING_FROM_STORAGE',
    EDITING_BASIC: 'EDITING_BASIC',
    EDITING_BASIC_FAIL: 'EDITING_BASIC_FAIL',
    EDITING_BASIC_SUCCESS: 'EDITING_BASIC_SUCCESS',
    EDITING_PROFILE: 'EDITING_PROFILE',
    EDITING_PROFILE_SUCCESS: 'EDITING_PROFILE_SUCCESS',
    EDITING_PROFILE_FAIL: 'EDITING_PROFILE_FAIL',
    EDITING_MATCH_PROFILE: 'EDITING_MATCH_PROFILE',
    EDITING_MATCH_PROFILE_SUCCESS: 'EDITING_MATCH_PROFILE_SUCCESS',
    EDITING_MATCH_PROFILE_FAIL: 'EDITING_MATCH_PROFILE_FAIL',
    SWIPING_LEFT: 'SWIPING_LEFT',
    SWIPE_LEFT_SUCCESS: 'SWIPE_LEFT_SUCCESS',
    SWIPE_LEFT_FAIL: 'SWIPE_LEFT_FAIL',
    SWIPING_RIGHT: 'SWIPING_RIGHT',
    SWIPE_RIGHT_FAIL: 'SWIPE_RIGHT_FAIL',
    SWIPE_RIGHT_SUCCESS: 'SWIPE_RIGHT_SUCCESS',
    
    UPLOADING_IMG: 'UPLOADING_IMG',
    IMG_UPLOAD_SUCCESS: 'IMG_UPLOAD_SUCCESS',
    IMG_UPLOAD_FAIL: 'IMG_UPLOAD_FAIL',

    GETTING_CANDIDATES: 'GETTING_CANDIDATES',
    GETTING_CANDIDATES_FAIL: 'GETTING_CANDIDATES_FAIL',
    GETTING_CANDIDATES_SUCCESS: 'GETTING_CANDIDATES_SUCCESS'
};

export const RecruiterConstants = {
    GETTING_RECRUITER_PROFILE:'GETTING_RECRUITER_PROFILE',
    GET_RECRUITER_PROFILE_SUCCESS:'GET_RECRUITER_PROFILE_SUCCESS',
    GET_RECRUITER_PROFILE_FAIL:'GET_RECRUITER_PROFILE_FAIL',

    GETTING_RECRUITERS:'GETTING_RECRUITERS',
    GETTING_RECRUITERS_SUCCESS:'GETTING_RECRUITERS_SUCCESS',
    GETTING_RECRUITERS_FAIL:'GETTING_RECRUITERS_FAIL',

    EDITING_RECRUITER_PROFILE:'EDITING_RECRUITER_PROFILE',
    RECRUITER_PROFILE_EDIT_SUCCESS:'RECRUITER_PROFILE_EDIT_SUCCESS',
    RECRUITER_PROFILE_EDIT_FAIL:'RECRUITER_PROFILE_EDIT_FAIL',

    RECRUITER_SWIPING:'RECRUITER_SWIPING',
    RECRUITER_SWIPE_RIGHT:'RECRUITER_SWIPE_RIGHT',
    RECRUITER_SWIPE_LEFT:'RECRUITER_SWIPE_LEFT',
    RECRUITER_SWIPE_FAIL:'RECRUITER_SWIPE_FAIL',

    VERIFY_AS_RECRUITER_EMAIL_SENT:'VERIFY_AS_RECRUITER_EMAIL_SENT'
};

export const StudentConstants = {
    GETTING_STUDENTS:'GETTING_STUDENTS',
    GETTING_STUDENTS_FAIL:'GETTING_STUDENTS_FAIL',
    GETTING_STUDENTS_SUCCESS:'GETTING_STUDENTS_SUCCESS',
    
    GETTING_STUDENT_PROFILE:'GETTING_STUDENT_PROFILE',
    GETTING_STUDENT_PROFILE_FAIL:'GETTING_STUDENT_PROFILE_FAIL',
    GETTING_STUDENT_PROFILE_SUCCESS:'GETTING_STUDENT_PROFILE_SUCCESS',

    EDITING_STUDENT_PROFILE:'EDITING_STUDENT_PROFILE',
    STUDENT_PROFILE_EDIT_SUCCESS:'STUDENT_PROFILE_EDIT_SUCCESS',
    STUDENT_PROFILE_EDIT_FAIL:'STUDENT_PROFILE_EDIT_FAIL',

    STUDENT_SWIPING:'STUDENT_SWIPING',
    STUDENT_SWIPE_RIGHT:'STUDENT_SWIPE_RIGHT',
    STUDENT_SWIPE_LEFT:'STUDENT_SWIPE_LEFT',
    STUDENT_SWIPE_FAIL:'STUDENT_SWIPE_FAIL',
};

export const EmployerConstants = {
    GETTING_EMPLOYER_PROFILE:'GETTING_EMPLOYER_PROFILE',
    GETTING_EMPLOYER_PROFILE_FAIL:'GETTING_EMPLOYER_PROFILE_FAIL',
    GETTING_EMPLOYER_PROFILE_SUCCESS:'GETTING_EMPLOYER_PROFILE_SUCCESS',

    GETTING_EMPLOYERS:'GETTING_EMPLOYERS',
    GETTING_EMPLOYERS_FAIL:'GETTING_EMPLOYERS_FAIL',
    GETTING_EMPLOYERS_SUCCESS:'GETTING_EMPLOYERS_SUCCESS',

    EDITING_EMPLOYER_PROFILE:'EDITING_EMPLOYER_PROFILE',
    EDITING_EMPLOYER_PROFILE_FAIL:'EDITING_EMPLOYER_PROFILE_FAIL',
    EDITING_EMPLOYER_PROFILE_SUCCESS:'EDITING_EMPLOYER_PROFILE_SUCCESS',

    VERIFYING_RECRUITER:'VERIFYING_RECRUITER',
    VERIFYING_RECRUITER_SUCCESS:'VERIFYING_RECRUITER_SUCCESS',
    VERIFYING_RECRUITER_FAIL:'VERIFYING_RECRUITER_FAIL',

    EMPLOYER_STUDENT_SWIPE_RIGHT:'EMPLOYER_STUDENT_SWIPE_RIGHT',
    EMPLOYER_STUDENT_SWIPE_LEFT:'EMPLOYER_STUDENT_SWIPE_LEFT',
    EMPLOYER_STUDENT_SWIPE_FAIL:'EMPLOYER_STUDENT_SWIPE_FAIL',
    EMPLOYER_SWIPING: 'EMPLOYER_SWIPING',

    EMPLOYER_CREATING_JOB:'EMPLOYER_CREATING_JOB',
    EMPLOYER_CREATE_JOB_SUCCESS:'EMPLOYER_CREATE_JOB_SUCCESS',
    EMPLOYER_CREATE_JOB_FAIL:'EMPLOYER_CREATE_JOB_FAIL',

    EMPLOYER_EDITING_JOB:'EMPLOYER_EDITING_JOB',
    EMPLOYER_EDITING_JOB_SUCCESS:'EMPLOYER_EDITING_JOB_SUCCESS',
    EMPLOYER_EDITING_JOB_FAIL:'EMPLOYER_EDITING_JOB_FAIL',

    EMPLOYER_REMOVING_JOB:'EMPLOYER_REMOVING_JOB',
    EMPLOYER_REMOVING_JOB_SUCCESS:'EMPLOYER_REMOVING_JOB_SUCCESS',
    EMPLOYER_REMOVING_JOB_FAIL:'EMPLOYER_REMOVING_JOB_FAIL',

    ASSIGNING_RECRUITER_JOB:'ASSIGNING_RECRUITER_JOB',
    ASSIGN_RECRUITER_JOB_FAIL:'ASSIGN_RECRUITER_JOB_FAIL',
    ASSIGN_RECRUITER_JOB_SUCCESS:'ASSIGN_RECRUITER_JOB_SUCCESS',

    SEARCHING_EMPLOYERS: 'SEARCHING_EMPLOYERS',
    SEARCH_QUERY_SUCCESS: 'SEARCH_QUERY_SUCCESS',
    SEARCH_QUERY_FAIL: 'SEARCH_QUERY_FAIL'
};

export const JobConstants = {
    GETTING_JOBS:'GETTING_JOBS',
    GETTING_JOBS_SUCCESS:'GETTING_JOBS_SUCCESS',
    GETTING_JOBS_FAIL:'GETTING_JOBS_FAIL',

    GETTING_SINGLE_JOB:'GETTING_SINGLE_JOB',
    GETTING_SINGLE_JOB_SUCCESS:'GETTING_SINGLE_JOB_SUCCESS',
    GETTING_SINGLE_JOB_FAIL:'GETTING_SINGLE_JOB_FAIL',

};
